version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    open-pull-requests-limit: 20
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Europe/London"
    ignore:
      - dependency-name: "@openactive/*"
    groups:
      eslint:
        dependency-type: "development"
        patterns:
        - "eslint*"
      jasmine:
        dependency-type: "development"
        patterns:
        - "jasmine*"
