name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  repository_dispatch:
    types: [data-models-update]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14
    - name: Install
      run: npm install
    - name: Test
      run: npm test
      
  deploy-site:
    needs: test
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    steps:
    - name: Deploy validator to Heroku
      uses: behe/heroku-build@v1
      with:
        app-name: "data-model-validator-staging"
        api-key: "${{secrets.HEROKU_API_KEY}}"
