name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  repository_dispatch:
    types: [data-models-update]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14
    - name: Install
      run: npm install
    - name: Test
      run: npm test
      
  deploy-site:
    needs: test
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Validator App
      uses: actions/checkout@v2
      with:
        repository: openactive/data-model-validator-site
        
    - name: Deploy
      uses: CDNievas/heroku-action@v1.0
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "data-model-validator-staging"
        heroku_email: "services@openactive.io"
        useforce: true
        
