name: Test and Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  repository_dispatch:
    types: [data-models-update]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14
    - name: Install
      run: npm install
    - name: Test
      run: npm test
      
  deploy-site:
    needs: test
    if: ${{ github.ref == 'refs/heads/master' }}
    concurrency: 
      group: validator-staging.openactive.io
      cancel-in-progress: true
    environment: validator-staging.openactive.io
    runs-on: ubuntu-latest
    steps:
    - name: Checkout validator app
      uses: actions/checkout@v2
      with:
        repository: openactive/data-model-validator-site
        path: data-model-validator-site
        
    - name: Deploy validator app to Heroku
      uses: behe/heroku-build@v1
      with:
        app-name: data-model-validator-staging
        api-key: "${{secrets.HEROKU_API_KEY}}"
        path: data-model-validator-site

  promote-site:
    needs: deploy-site
    if: ${{ github.ref == 'refs/heads/master' }}
    concurrency: 
      group: validator.openactive.io
      cancel-in-progress: true
    environment: validator.openactive.io
    runs-on: ubuntu-latest
    steps:
    - name: Promote validator app to production
      uses: tiltshift/heroku-promote-app@v1
      with:
        heroku_app_name: data-model-validator-staging
        heroku_api_key: "${{secrets.HEROKU_API_KEY}}"
        heroku_email: "services@openactive.io"

