name: Test

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js 18.17.1
      uses: actions/setup-node@v1
      with:
        node-version: 18.17.1
    - name: Install
      run: npm install
    - name: Test
      run: npm test
