name: Run OpenActive Test Suite

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  openactive-test-suite:
    uses: openactive/openactive-test-suite/.github/workflows/test-and-publish.yml@master
    with:
      quick_test: true
      data-model-validator_ref: ${{ github.ref }}
